### ISSUE TITLE
Broken on Rails 6.1

### ISSUE THREAD

**Issue by KieranP** [mufid/rails-static-router#2]
Tried to use this today. Getting this error:

`uninitialized constant ActionDispatch::Routing::Endpoint (NameError)`

Seems like Rails 6.1 removed the Endpoint class.

**Comment by mufid** [comment]
Thanks for reporting. What version do you use? On Rails 6.1 it shows different error for me on test:

```
Failures:

  1) Integration Test can respond to static routes
     Failure/Error: env["PATH_INFO"] = @file_handler.match?(path)
     
     NoMethodError:
       undefined method `match?' for #<ActionDispatch::FileHandler:0x0000563d474a0738>
     # ./lib/action_dispatch/routing/static_responder.rb:95:in `call'
     # /home/fidvm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.1.0/lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
     # /home/fidvm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.1.0/lib/action_dispatch/routing/mapper.rb:49:in `serve'
     # /home/fidvm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.1.0/lib/action_dispatch/journey/router.rb:50:in `block in serve'
     # /home/fidvm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.1.0/lib/action_dispatch/journey/router.rb:32:in `each'
```
